config/routes.rb
MusicApp::Application.routes.draw do
  root to: 'sessions#new'

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  get '/users/activate?token=:token' => 'users#activate',
    as: "activate_user",
    path: 'users/activate'

  resources :bands, shallow: true,  do
    resources :albums, shallow: true do
      resources :tracks, shallow: true do
        resource :note
      end
    end
  end
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :body, :track_id

  belongs_to :track
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def create
    @note = Note.new(params[:note])
    if @note.save
      redirect_to track_url(params[:track_id])
    else
      flash[:notice] = "That note has already been added."
      render track_url(params[:track_id])
    end
  end

  def update
    current_note.update_attributes(params[:note])
    redirect_to track_url(params[:track_id])
  end

  def destroy

  end

  private

  def current_note
    Track.find(params[:track_id]).note
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_note.html.erb
<% action = track_note_url(track) %>
<% method = (note.persisted? ? :put : :post) %>
<% button_text = (note.persisted? ? "Edit note" : "Add note") %>

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="hidden" name="note[track_id]" value="<%= track.id %>">

  <label>
    Notes:
    <br>
    <textarea
      name="note[body]"
      value="<%= note.body %>">
      <%= note.body %>
    </textarea>
  </label>
  <br>
  <input type="submit" value="<%= button_text %>">
</form>