config/routes.rb
MusicApp::Application.routes.draw do
  root to: 'sessions#new'

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  get '/users/activate?token=:token' => 'users#activate',
    as: "activate_user",
    path: 'users/activate'

  resources :bands, shallow: true,  do
    resources :albums, shallow: true do
      resources :tracks, shallow: true do
        resource :note
      end
    end
  end
end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :album_id, :name, :track_number, :bonus, :lyrics, :length

  validates :name, :album_id, :length_in_seconds, presence: true
  validates :bonus, presence: { in: %w(yes no)}
  validates :name, :track_number, uniqueness: true

  belongs_to :album
  has_one :note

  def length=(length)
    @length = length
    time_array = @length.split(":").map(&:to_i)
    self.length_in_seconds = time_array.first * 60 + time_array.last
  end

  def formatted_length
    seconds = self.length_in_seconds
    "#{seconds / 60}:#{seconds % 60}"
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def index
    @album = Album.find(params[:album_id])
    @band = @album.band
    @album_tracks = @album.tracks
  end

  def show
    current_track
    current_album
    current_band
    @note = (current_track.note.nil? ? Note.new : current_track.note)
  end

  def new
    @album = Album.find(params[:album_id])
    @band_albums = @album.band.albums
    @track = Track.new
  end

  def edit
    current_track
    current_album
    @band_albums = current_band.albums
  end

  def create
    @track = Track.new(params[:track])
    @album = @track.album
    @band_albums = @album.band.albums
    if @track.save
      redirect_to album_url(@track)
    else
      flash[:notice] = "That track has already been added."
      render :new
    end
  end

  def update
    current_track.update_attributes(params[:track])
    redirect_to track_url(current_track)
  end

  def destroy
    album = Track.find(params[:id]).album
    Track.delete(params[:id])

    redirect_to album_url(album)
  end

  private

  def current_track
    @track = Track.find(params[:id])
  end

  def current_album
    @album = current_track.album
  end

  def current_band
    @band = current_album.band
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_form.html.erb
<% action = (track.persisted? ? track_url(track) : album_tracks_url) %>
<% method = (track.persisted? ? :put : :post) %>
<% heading = (track.persisted? ?  "Edit a track" : "Add a track") %>
<% button_text = (track.persisted? ? "Update track" : "Add track") %>
<% url = (track.persisted? ? track_url(track) : album_url(album)) %>

<h1><%= heading %></h1>
<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="hidden" name="track[album_id]" value="<%= album.id %>">

  <label>
    Album Name:
    <select name="track[album_id]">
      <option></option>
      <% @band_albums.each do |band_album| %>
        <option
          value="<%= band_album.id %>"
          <%= "selected" if band_album.id == album.id %>>
          <%= band_album.name %>
        </option>
      <% end %>
    </select>
   </label>
  <br>
  <label>
    Track No.:
    <input
      type="text"
      name="track[track_number]"
      value="<%= track.track_number %>">
  </label>
  <br>
  <label>
    Track Name:
    <input type="text" name="track[name]" value="<%= track.name %>">
  </label>
  <br>
  <label>
    Track Length(mm:ss):
    <input type="text"
      name="track[length]"
      value="<%= track.formatted_length if track.persisted? %>">
  </label>
  <br>
  <label>
    Bonus Track:
    <% %w(yes no).each do |option| %>
      <label>
        <%= option.camelize %>
        <input type="radio"
          name="track[bonus]"
          value="<%= option %>"
          <%= track.bonus == option ? "checked" : "" %>>
      </label>
    <% end %>
  </label>
  <br>
  <label>
    Lyrics:
    <br>
    <textarea
      name="track[lyrics]"
      value="<%= track.lyrics %>">
      <%= track.lyrics %>
    </textarea>
  </label>
  <br>
  <input type="submit" value="<%= button_text %>">
</form>
<%= button_to "Cancel", url, method: :get %>

app/views/tracks/edit.html.erb
<%= render "form", track: @track, album: @album, band_albums: @band_albums %>

app/views/tracks/index.html.erb
<h1><%= adds_s(@album.name) %> Tracks</h1>

<% @album.tracks.each do |track| %>

<% end %>

app/views/tracks/new.html.erb
<%= render "form", track: @track, album: @album, band_albums: @band_albums %>

app/views/tracks/show.html.erb
<h1><%= @track.name %></h1>

<table>
  <tr>
    <td>Album Name:</td>
    <td><%= @track.album.name %></td>
  </tr>
  <tr>
    <td>Track No.:</td>
    <td><%= @track.track_number %></td>
  </tr>
  <tr>
    <td>Track Length:</td>
    <td><%= @track.formatted_length %></td>
  </tr>
  <tr>
    <td>Bonus Track:</td>
    <td><%= @track.bonus.camelize %></td>
  </tr>
</table>

<p>Lyrics:</p>
<p>
<%= @track.lyrics %>
</p>

<%= render '/notes/note', track: @track, note: @note %>

<br>
<%= link_to "Edit Track", edit_track_url(@track) %>
<br>
<%= link_to @album.name, album_url(@album) %>
<br>
<%= link_to @band.name, band_url(@band) %>
<br>
<% if is_admin? %>
  <%= button_to "Delete Track", track_url(@track), method: :delete %>
<% end %>