config/routes.rb
MusicApp::Application.routes.draw do
  root to: 'sessions#new'

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  get '/users/activate?token=:token' => 'users#activate',
    as: "activate_user",
    path: 'users/activate'

  resources :bands, shallow: true,  do
    resources :albums, shallow: true do
      resources :tracks, shallow: true do
        resource :note
      end
    end
  end
end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :band_id, :name, :live_or_studio

  validates :band_id, :name, presence: true
  validates :live_or_studio, presence: { in: %w(live studio)}
  validates :name, uniqueness: true

  belongs_to :band
  has_many :tracks
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @band = Band.find(current_band)
    @band_albums = @band.albums
  end

  def show
    @album = current_album
    @band = @album.band
  end

  def new
    @band = current_band
    @album = Album.new
  end

  def edit
    @album = current_album
    @band = @album.band
  end

  def create
    @album = Album.new(params[:album])
    if @album.save
      redirect_to album_url(@album)
    else
      flash[:notice] = "That album has already been added."
      render :new
    end
  end

  def update
    current_album.update_attributes(params[:album])
    redirect_to album_url(current_album)
  end

  def destroy
    band = Album.find(params[:id]).band
    Album.delete(params[:id])

    redirect_to band_albums_url(band)
  end

  private

  def current_album
    @album = Album.find(params[:id])
  end

  def current_band
    @band = Band.find(params[:band_id])
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<% action = (album.persisted? ? album_url(album) : band_albums_url) %>
<% method = (album.persisted? ? :put : :post) %>
<% heading = (album.persisted? ? "Edit an Existing Album" : "Add a New Album") %>
<% button_text = (album.persisted? ? "Edit Album" : "Add Album") %>
<% url = (album.persisted? ? album_url(album) : band_url(band)) %>
<% type = album.live_or_studio %>

<h1><%= heading %></h1>

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value ="<%= method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label>
    Band Name:
    <select name="album[band_id]">
      <option></option>
      <% Band.all.each do |band| %>
        <option value="<%= band.id %>" <%= "selected" if band == @band %>>
          <%= band.name %>
        </option>
      <% end %>
    </select>
  </label>
  <br>
  <label>
    Album Name:
    <input type="text" name="album[name]" value="<%= album.name %>">
  </label>
  <br>

  <label>
    Album Type:
    <% %w(live studio).each do |option| %>
      <label>
        <%= option.camelize %>
        <input type="radio"
          name="album[live_or_studio]"
          value="<%= option %>"
          <%= type == option ? "checked" : "" %>>
      </label>
    <% end %>
  </label>

  <br>

  <input type="submit" value="<%= button_text %>">
</form>

<%= button_to "Cancel", url, method: :get %>

app/views/albums/edit.html.erb
<%= render "form", album: @album, band: @band %>

app/views/albums/index.html.erb
<h1><%= adds_s(@band.name) %> Albums</h1>

<ul>
  <% @band_albums.each do |band_album| %>
    <li>
      <%= link_to band_album.name, album_url(band_album) %>
    </li>
  <% end %>
</ul>

<%= link_to "Add album", new_band_album_url(@band.id) %>
<br>
<%= link_to @band.name, band_url(@band) %>
<br>
<%= link_to "Back to All Bands", bands_url %>

app/views/albums/new.html.erb
<%= render "form", album: @album, band: @band %>

app/views/albums/show.html.erb
<h1><%= @album.name %></h1>

<p><%= "#{@album.live_or_studio.camelize} Album" %></p>
<table>
  <th>Track No.</th>
  <th>Track Name</th>
  <th>Length</th>
  <% @album.tracks.each do |track| %>
  <% bonus = (track.bonus == "yes" ? "*" : "") %>
  <% link_to_track = (link_to "#{bonus}#{track.name}", track_url(track)) %>
    <tr>
      <td align="center"><%= track.track_number %></td>
      <td align="center"><%= link_to_track %></td>
      <td align="center"><%= track.formatted_length %></td>
    </tr>
  <% end %>
</table>
<p>* = Bonus Track</p>

<%= link_to "Add Track", new_album_track_url(@album) %>
<br>
<%= link_to "Edit Album", edit_album_url(@album) %>
<br>
<%= link_to "All Albums for #{@band.name}", band_albums_url(@band) %>
<br>
<%= link_to @band.name, band_url(@band) %>
<br>
<% if is_admin? %>
  <%= button_to "Delete Album", album_url(@album), method: :delete %>
<% end %>