config/routes.rb
MusicApp::Application.routes.draw do
  root to: 'sessions#new'

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  get '/users/activate?token=:token' => 'users#activate',
    as: "activate_user",
    path: 'users/activate'

  resources :bands, shallow: true,  do
    resources :albums, shallow: true do
      resources :tracks, shallow: true do
        resource :note
      end
    end
  end
end

app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :name

  validates :name, presence: true, uniqueness: true

  has_many :albums
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
  end

  def show
    @band = Band.find(params[:id])
    @albums = @band.albums
  end

  def new
    @band = Band.new
  end

  def edit
    @band = current_band
  end

  def create
    @band = Band.new(params[:band])
    if @band.save
      redirect_to band_url(@band)
    else
      flash[:notice] = "That band has already been added."
      render :new
    end
  end

  def update
    current_band.update_attributes(params[:band])
    redirect_to band_url(current_band)
  end

  def destroy
    Band.delete(params[:id])

    redirect_to bands_url
  end

  private

  def current_band
    @current_band ||= Band.find(params[:id])
  end
end

app/helpers/bands_helper.rb
module BandsHelper

  def live(album)
    album.live_or_studio == "live" ? "(live)" : ""
  end
end

app/views/bands/_form.html.erb
<% action = (band.persisted? ? band_url(band) : bands_url) %>
<% method = (band.persisted? ? :put : :post) %>
<% heading = (band.persisted? ?  "Edit a band" : "Add a band") %>
<% button_text = (band.persisted? ? "Update band" : "Add band") %>
<% url = (band.persisted? ? band_url(band) : bands_url) %>

<h1><%= heading %></h1>
<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label>
    Band Name:
    <input type="text" name="band[name]" value="<%= band.name %>">
  </label>
  <br>

  <input type="submit" value="<%= button_text %>">
</form>
<%= button_to "Cancel", url, method: :get %>

app/views/bands/edit.html.erb
<%= render "form", band: @band %>

app/views/bands/index.html.erb
<h1>Bands List</h1>

<ul>
  <% @bands.each do |band| %>
    <li>
      <%= link_to band.name, band_url(band) %>
    </li>
  <% end %>
</ul>

<%= link_to "Add a band", new_band_url %>

app/views/bands/new.html.erb
<%= render "form", band: @band %>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

<ul>
  <% @albums[0..4].each do |album| %>
  <li>
    <%= link_to "#{album.name}#{live(album)}", album_url(album) %>
  </li>
  <% end %>
</ul>
<br>
<%= link_to "More albums", band_albums_url(@band.id) %>
<br>
<%= link_to "Add album", new_band_album_url(@band.id) %>
<br>
<%= link_to "Edit Band", edit_band_url(@band) %>
<br>
<%= link_to "Back to All Bands", bands_url %>
<br>
<% if is_admin? %>
  <%= button_to "Delete Band", band_url(@band), method: :delete %>
<% end %>